import Head from "next/head";
import Image from "next/image";
import { useEffect, useState, useMemo } from "react";
import Timer from "../components/Timer";
import Trivia from "../components/Trivia";
import Styles from "../styles/Home.module.css";
import Start from "../components/Start";
import { toast, ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export default function Home() {
  const [username, setUsername] = useState(null);
  const [questionNumber, setQuestionNumber] = useState(1);
  const [stop, setStop] = useState(false);
  const [earned, setEarned] = useState(" 0");
  const [data, setData] = useState([]);
  const [time, setTime] = useState(new Date().getTime());

  useEffect(() => {
    fetch("https://kbcapp-jitendra895.vercel.app/api/getQuestions")
      .then((res) => res.json())
      .then((data) => {
        setData(data.question);
        console.log(data.question);
      });
  }, []);

  useEffect(() => {
    fetch("https://kbcapp-jitendra895.vercel.app/api/getCountdownTime")
      .then((res) => res.json())
      .then((tim) => {
        setTime(new Date(tim.time[0].time));
        console.log(tim);
      });
  }, []);

  const submitResults = async (e) => {
    e.preventDefault();
    const result = { userName: username, score: earned };
    let res = await fetch("https://kbcapp-jitendra895.vercel.app/api/addResult", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(result),
    });
    let response = await res.json();
    console.log(response);
    if (response.success) {
      toast.success("Score submitted successfully!!", {
        position: "top-left",
        autoClose: 3000,
        hideProgressBar: false,
        closeOnClick: true,
        pauseOnHover: true,
        draggable: true,
        progress: undefined,
        theme: "light",
      });
    } else {
      toast.error(response.error, {
        position: "top-left",
        autoClose: 3000,
        hideProgressBar: false,
        closeOnClick: true,
        pauseOnHover: true,
        draggable: true,
        progress: undefined,
        theme: "light",
      });
    }
  };

  const moneyPyramid = useMemo(
    () =>
      [
        { id: 1, amount: " 10" },
        { id: 2, amount: " 20" },
        { id: 3, amount: " 30" },
        { id: 4, amount: " 40" },
        { id: 5, amount: " 50" },
        { id: 6, amount: "60" },
        { id: 7, amount: " 70" },
        { id: 8, amount: " 80" },
        { id: 9, amount: "90" },
        { id: 10, amount: "100" },
        { id: 11, amount: "110" },
        { id: 12, amount: " 120" },
        { id: 13, amount: " 130" },
        { id: 14, amount: "140" },
        { id: 15, amount: "150" },
      ].reverse(),
    []
  );
  useEffect(() => {
    questionNumber > 1 &&
      setEarned(moneyPyramid.find((m) => m.id === questionNumber - 1).amount);
  }, [questionNumber]);

  return (

    <div className={Styles.app}>
      <Head>
        <title>Crorepati</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ToastContainer
        position="top-left"
        autoClose={3000}
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover
        theme="light"
      />
      <ToastContainer />
      {username ? (
        <>
          <div className={Styles.main}>
            {stop ? (
              <h1 className={Styles.endtext}>
                You Scored:{earned}{" "}
                <button onClick={submitResults} className="submitButton">
                  submit
                </button>
              </h1>
            ) : (
              <>
                <div className={Styles.top}>
                  <div className={Styles.timer}>
                    <Timer setStop={setStop} questionNumber={questionNumber} />
                  </div>
                </div>
                <div className={Styles.bottom}>
                  <Trivia
                    data={data}
                    setStop={setStop}
                    questionNumber={questionNumber}
                    setQuestionNumber={setQuestionNumber}
                  />
                </div>
              </>
            )}
          </div>
          <div className={Styles.pyramid}>
            <div className={Styles.avatar}>
              <Image src="/boy.png" alt={username} width={50} height={50} />
              <h1>{username}</h1>
            </div>

            <ul className={Styles.moneyList}>
              {moneyPyramid.map((m) => (
                <li
                  className={
                    questionNumber === m.id
                      ? "moneyListItem active"
                      : "moneyListItem"
                  }
                  key={m.id}
                >
                  <span className={Styles.moneyListItemNumber}>{m.id}</span>
                  <span className={Styles.moneyListItemAmount}>{m.amount}</span>
                </li>
              ))}
            </ul>
          </div>
        </>
      ) : (
        <>
          <Start setUsername={setUsername} targetDate={time} />
        </>
      )}
    </div>
  );
}
